In [31]:
import pandas as pd

# SILVR + EDM, fragments 0072 + 0107
experiment_names = ['exp_9','exp_10','exp_11','exp_12','exp_13','exp_14','exp_15']

# BRIDGE + EDM, fragments 0072 + 0107
# experiment_names = ['exp_16','exp_17','exp_18','exp_19','exp_20','exp_21','exp_22']

# BRIDGE + EDM, fragments 0072 + 0107 (250 SAMPLES)
# experiment_names = ['exp_23','exp_24','exp_25','exp_26','exp_27','exp_28','exp_29']
# BRIDGE + EDM, fragments 0072 + 0107 (Explicit Hydrogens)
# experiment_names = ['exp_30','exp_31','exp_32','exp_33','exp_34','exp_35','exp_36']
df = pd.read_csv(f"experiments/{experiment_names[0]}_to_{experiment_names[-1]}_data_all.csv")
len(df)

728

In [15]:
'''
These are the experiments I'd like to visualise in pymol
SILVR - top-scoring molecule from r_s = 0, exp_9
top-scoring molecule from r_s = 2, exp_14

BRIDGE - top-scoring molecule from r_s = 0, exp_16
top-scoring molecule from r_s = 0.25 or  0.5 exp_18ï¼Œ exp_19
'''
experiments_to_visualise = ['exp_9','exp_14','exp_16','exp_18','exp_19']
#read in the pd dataframes for the experiments
df_list = [f"{x}_mpro_vina_docking_data.csv" for x in experiments_to_visualise]

top_scoring_molecules_df = pd.DataFrame()
for df_name in df_list:
    vina_results_df = pd.read_csv(f"{df_name}")
    if vina_results_df.columns[0] != 'ligand_name':
        vina_results_df = vina_results_df.iloc[1:]
        #drop the error_message column
        vina_results_df = vina_results_df.drop(columns=['error_message'])
        #rename the columns
        vina_results_df = vina_results_df.rename(columns={'computed_dG':'error_message','protein_name':'computed_dG','ligand_name':'protein_name','Unnamed: 0':'ligand_name'})

    # printout the top-scoring molecule for each experiment
    top_scoring_molecule = vina_results_df.sort_values(by='computed_dG', ascending=True).head(1)
    # top_scoring_molecule_df is a dataframe with 3 columns: exp_id, ligand_name and computed_dG
    top_scoring_molecules_df = pd.concat([top_scoring_molecules_df, top_scoring_molecule]) 
    
top_scoring_molecules_df

                   ligand_name  protein_name computed_dG error_message  exp_id
25  mol_2024_07_09_1139090_000  Mpro-protein      -7.022           NaN   exp_9
7   mol_2024_07_09_1355351_000  Mpro-protein       -8.28           NaN  exp_14
53  mol_2024_07_09_1457441_000  Mpro-protein      -6.869           NaN  exp_16
22  mol_2024_07_09_1606472_000  Mpro-protein      -3.267           NaN  exp_18
96  mol_2024_07_09_1630113_000  Mpro-protein       -4.11           NaN  exp_19

In [34]:
'''
These are the experiments I'd like to visualise in pymol
SILVR - top-scoring molecule from each SILVR rate, exp_9, exp_10, exp_11, exp_12, exp_13, exp_14, exp_15
'''
experiments_to_visualise = ['exp_9','exp_10','exp_11','exp_12','exp_13','exp_14','exp_15']
#read in the pd dataframes for the experiments
df_list = [f"{x}_mpro_vina_docking_data.csv" for x in experiments_to_visualise]

top_scoring_molecules_df_vina = pd.DataFrame()
for df_name in df_list:
    vina_results_df = pd.read_csv(f"{df_name}")
    if vina_results_df.columns[0] != 'ligand_name':
        vina_results_df = vina_results_df.iloc[1:]
        #drop the error_message column
        vina_results_df = vina_results_df.drop(columns=['error_message'])
        #rename the columns
        vina_results_df = vina_results_df.rename(columns={'computed_dG':'error_message','protein_name':'computed_dG','ligand_name':'protein_name','Unnamed: 0':'ligand_name'})

    # printout the top-scoring molecule for each experiment
    top_scoring_molecule = vina_results_df.sort_values(by='computed_dG', ascending=True).head(1)
    # top_scoring_molecule_df is a dataframe with 3 columns: exp_id, ligand_name and computed_dG
    top_scoring_molecules_df_vina = pd.concat([top_scoring_molecules_df_vina, top_scoring_molecule]) 
    
top_scoring_molecules_df_vina

,ligand_name,protein_name,computed_dG,error_message,exp_id
25,mol_2024_07_09_1139090_000,Mpro-protein,-7.022,NaN,exp_9
19,mol_2024_07_09_1155343_000,Mpro-protein,-6.761,NaN,exp_10
82,mol_2024_07_09_1236203_000,Mpro-protein,-6.844,NaN,exp_11
74,mol_2024_07_09_1250023_000,Mpro-protein,-6.990,NaN,exp_12
57,mol_2024_07_09_1317173_000,Mpro-protein,-8.005,NaN,exp_13
7,mol_2024_07_09_1355351_000,Mpro-protein,-8.280,NaN,exp_14
45,mol_2024_07_09_1413183_000,Mpro-protein,-8.221,NaN,exp_15

In [37]:
'''
These are the experiments I'd like to visualise in pymol
SILVR - top-scoring molecule from each SILVR rate, exp_9, exp_10, exp_11, exp_12, exp_13, exp_14, exp_15
'''
experiments_to_visualise = ['exp_9','exp_10','exp_11','exp_12','exp_13','exp_14','exp_15']
#read in the pd dataframes for the experiments
df_list = [f"{x}_mpro_oe_docking_data.csv" for x in experiments_to_visualise]

oe_match_vina = pd.DataFrame()
for df_name in df_list:
    oe_results_df = pd.read_csv(f"{df_name}")
    if oe_results_df.columns[0] != 'ligand_name':
        oe_results_df = oe_results_df.iloc[1:]
        #drop the error_message column
        oe_results_df = oe_results_df.drop(columns=['error_message'])
        #rename the columns
        oe_results_df = oe_results_df.rename(columns={'computed_dG':'error_message','protein_name':'computed_dG','ligand_name':'protein_name','Unnamed: 0':'ligand_name'})
            # get rid of the _0 in the ligand_name column
        oe_results_df['ligand_name'] = oe_results_df['ligand_name'].str.replace(r'(_0)$', '',regex=True)

    # print out the matching ligands between top scoring molecules from vina and oe_results_df
    # oe_match = pd.merge(top_scoring_molecules_df_vina, oe_results_df, on='ligand_name')
    # oe_match_vina = pd.concat([oe_match_vina, oe_match])

    oe_match = oe_results_df[oe_results_df['ligand_name'].isin(top_scoring_molecules_df_vina['ligand_name'])]
    oe_match_vina = pd.concat([oe_match_vina, oe_match])

    
oe_match_vina

Empty DataFrame
Columns: [ligand_name, protein_name, computed_dG, error_message, exp_id]
Index: []

In [ ]:
top_scoring_molecules_vina_list = top_scoring_molecules_df_vina['ligand_name'].to_list()
# check if vina top-scoring molecules are in the oe top-scoring molecules
top_scoring_molecules_df['ligand_name'].isin(top_scoring_molecules_vina_list)

In [28]:
import os
top_scoring_molecules_vina_list = top_scoring_molecules_df_vina['ligand_name'].to_list()
for i in top_scoring_molecules_vina_list:
    os.system(f'cp -r docking_results/diffusion_model/exp_9_to_36/vina_docking/with_water/unsorted_data/*{i}* dissertation_figures/vina')

In [17]:
'''
These are the experiments I'd like to visualise in pymol
SILVR - top-scoring molecule from each SILVR rate, exp_9, exp_10, exp_11, exp_12, exp_13, exp_14, exp_15
'''
experiments_to_visualise = ['exp_9','exp_10','exp_11','exp_12','exp_13','exp_14','exp_15']
#read in the pd dataframes for the experiments
df_list = [f"{x}_mpro_oe_docking_data.csv" for x in experiments_to_visualise]

top_scoring_molecules_df_oe = pd.DataFrame()
for df_name in df_list:
    oe_results_df = pd.read_csv(f"{df_name}")
    if oe_results_df.columns[0] != 'ligand_name':
        oe_results_df = oe_results_df.iloc[1:]
        #drop the error_message column
        oe_results_df = oe_results_df.drop(columns=['error_message'])
        #rename the columns
        oe_results_df = oe_results_df.rename(columns={'computed_dG':'error_message','protein_name':'computed_dG','ligand_name':'protein_name','Unnamed: 0':'ligand_name'})

    # printout the top-scoring molecule for each experiment
    top_scoring_molecule = oe_results_df.sort_values(by='computed_dG', ascending=True).head(1)
    # top_scoring_molecule_df is a dataframe with 3 columns: exp_id, ligand_name and computed_dG
    top_scoring_molecules_df_oe = pd.concat([top_scoring_molecules_df_oe, top_scoring_molecule]) 
    
top_scoring_molecules_df_oe

,ligand_name,protein_name,computed_dG,error_message,exp_id
61,mol_2024_07_09_1132273_000_0,Mpro-protein,-8.430538,NaN,exp_9
34,mol_2024_07_09_1155343_000_0,Mpro-protein,-8.475809,NaN,exp_10
148,mol_2024_07_09_1231271_000_0,Mpro-protein,-7.308201,NaN,exp_11
97,mol_2024_07_09_1254022_000_0,Mpro-protein,-11.160748,NaN,exp_12
41,mol_2024_07_09_1330561_000_0,Mpro-protein,-13.310907,NaN,exp_13
27,mol_2024_07_09_1357330_000_0,Mpro-protein,-13.706440,NaN,exp_14
85,mol_2024_07_09_1408590_000_0,Mpro-protein,-13.507286,NaN,exp_15

In [ ]:
import os
top_scoring_molecules_oe_list = top_scoring_molecules_df_oe['ligand_name'].to_list()
for i in top_scoring_molecules_vina_list:
    os.system(f'cp -r docking_results/diffusion_model/exp_9_to_36/oe_docking/with_water/oe_docking_data/*{i}* dissertation_figures/oe')